name: CI/CD Pipeline

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Project
      run: |

  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Semgrep
      run: |
        # Install Semgrep
        curl -sL https://semgrep.dev/install.sh | sh
        export PATH=$PATH:$HOME/.local/bin

    - name: Run Static Analysis
      run: |
        # Run Semgrep static analysis
        semgrep --config my-semgrep-config.yml  # Add your Semgrep config file

  build-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      rules:
  - id: insecure-subprocess-call
    patterns:
      - pattern: |
          subprocess.call(os.getenv("COMMAND"))
    message: "Avoid using subprocess.call with user input"

  - id: hardcoded-secret
    patterns:
      - pattern: |
          SECRET_KEY = "supersecret"
    message: "Avoid hardcoding sensitive information like secret keys"


  deploy-to-kubernetes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure Kubectl
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Deploy to Kubernetes
      run: |
       

